import os
import sys
import time
import json
import random
from typing import List, Tuple, Dict, Any
from openai import OpenAI
from dotenv import load_dotenv
from tqdm import tqdm
from utils import (
    load_novel, 
    split_into_chapters, 
    split_into_chunks, 
    estimate_tokens,
    create_directories
)


class NovelSummarizerConfig:
    """Configuration class for the Novel Summarizer."""
    
    def __init__(self):
        # Load environment variables
        load_dotenv()
        
        # Default values
        self.api_base_url = os.getenv('LMSTUDIO_BASE_URL', 'http://100.119.66.104')
        self.api_port = int(os.getenv('LMSTUDIO_PORT', '18000'))
        self.model_name = os.getenv('MODEL_NAME', 'qwen3-8b')
        self.max_tokens = int(os.getenv('MAX_TOKENS', '32786'))  # Updated to 32786
        self.chunk_buffer = int(os.getenv('CHUNK_BUFFER', '500'))
        self.api_timeout = int(os.getenv('API_TIMEOUT', '60'))
        
        # Construct full API URL
        self.server_url = f"{self.api_base_url.rstrip(':')}:{self.api_port}"
        
    def get_full_api_url(self):
        """Get the full API URL with v1 endpoint."""
        return f"{self.server_url}/v1"
    
    def update_from_args(self, server_url=None, model=None, max_tokens=None):
        """Update configuration from command line arguments."""
        if server_url:
            self.server_url = server_url.rstrip('/')
            # Extract base URL and port if possible
            if ':' in server_url.replace('http://', '').replace('https://', ''):
                parts = server_url.replace('http://', '').replace('https://', '').split(':')
                if len(parts) >= 2:
                    protocol = 'http://' if 'http://' in server_url else 'https://'
                    self.api_base_url = f"{protocol}{parts[0]}"
                    self.api_port = int(parts[1].split('/')[0])  # Remove any path
        
        if model:
            self.model_name = model
            
        if max_tokens:
            self.max_tokens = max_tokens
    
    def __str__(self):
        """String representation of the configuration."""
        return (f"NovelSummarizerConfig(\n"
                f"  server_url='{self.server_url}',\n"
                f"  model_name='{self.model_name}',\n"
                f"  max_tokens={self.max_tokens},\n"
                f"  chunk_buffer={self.chunk_buffer}\n"
                f")")


class CheckpointManager:
    """Manages checkpoint files for resuming interrupted processing."""
    
    def __init__(self, novel_path: str, output_path: str):
        """Initialize checkpoint manager."""
        self.novel_path = novel_path
        self.output_path = output_path
        
        # Create checkpoint directory
        self.checkpoint_dir = "checkpoints"
        os.makedirs(self.checkpoint_dir, exist_ok=True)
        
        # Generate checkpoint filename based on input file
        base_name = os.path.splitext(os.path.basename(novel_path))[0]
        self.checkpoint_file = os.path.join(self.checkpoint_dir, f"{base_name}_checkpoint.json")
        self.progress_file = os.path.join(self.checkpoint_dir, f"{base_name}_progress.md")
    
    def save_checkpoint(self, chapter_index: int, total_chapters: int, 
                       processed_results: List[Tuple[str, str]], 
                       metadata: Dict[str, Any]):
        """Save current progress to checkpoint file."""
        checkpoint_data = {
            "novel_path": self.novel_path,
            "output_path": self.output_path,
            "chapter_index": chapter_index,
            "total_chapters": total_chapters,
            "processed_results": processed_results,
            "metadata": metadata,
            "timestamp": time.strftime('%Y-%m-%d %H:%M:%S')
        }
        
        with open(self.checkpoint_file, 'w', encoding='utf-8') as f:
            json.dump(checkpoint_data, f, ensure_ascii=False, indent=2)
        
        # Also save intermediate progress summary
        self._save_progress_summary(processed_results, chapter_index, total_chapters, metadata)
    
    def _save_progress_summary(self, results: List[Tuple[str, str]], 
                              current_index: int, total_chapters: int,
                              metadata: Dict[str, Any]):
        """Save intermediate progress summary in markdown format."""
        with open(self.progress_file, 'w', encoding='utf-8') as f:
            f.write(f"# 小说章节摘要 - 阶段性进度 (Generated by {metadata.get('model', 'Unknown')})\n\n")
            f.write(f"**原文件**: {self.novel_path}\n")
            f.write(f"**使用模型**: {metadata.get('model', 'Unknown')}\n")
            f.write(f"**服务器**: {metadata.get('server_url', 'Unknown')}\n")
            f.write(f"**生成时间**: {time.strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f"**进度**: {current_index}/{total_chapters} 章节已完成 ({current_index/total_chapters*100:.1f}%)\n")
            f.write(f"**已处理章节数**: {len(results)}\n\n")
            f.write("---\n\n")
            
            for title, summary in results:
                f.write(f"## {title}\n\n")
                f.write(f"**摘要**: {summary}\n\n")
            
            if current_index < total_chapters:
                f.write("---\n\n")
                f.write("**注意**: 这是阶段性进度保存，处理尚未完成。\n")
                f.write(f"剩余 {total_chapters - current_index} 个章节待处理。\n")
    
    def load_checkpoint(self) -> Tuple[bool, Dict[str, Any]]:
        """Load checkpoint if exists."""
        if os.path.exists(self.checkpoint_file):
            try:
                with open(self.checkpoint_file, 'r', encoding='utf-8') as f:
                    checkpoint_data = json.load(f)
                return True, checkpoint_data
            except Exception as e:
                print(f"⚠️ 加载断点文件失败: {e}")
                return False, {}
        return False, {}
    
    def clear_checkpoint(self):
        """Clear checkpoint files after successful completion."""
        for file_path in [self.checkpoint_file, self.progress_file]:
            if os.path.exists(file_path):
                try:
                    os.remove(file_path)
                except Exception as e:
                    print(f"⚠️ 删除断点文件失败: {e}")


class NovelSummarizer:
    """A class to handle novel summarization with rolling window approach using local LLM."""
    
    def __init__(self, config: NovelSummarizerConfig = None):
        """
        Initialize the summarizer for local LLM server.
        
        Args:
            config: Configuration object with all settings
        """
        if config is None:
            config = NovelSummarizerConfig()
        
        self.config = config
        
        # Initialize OpenAI client pointing to local LMStudio server
        self.client = OpenAI(
            base_url=config.get_full_api_url(),
            api_key="lm-studio"  # LMStudio doesn't require a real API key
        )
        
        # Calculate chunk parameters
        self.chunk_size = config.max_tokens - config.chunk_buffer
        self.stride = self.chunk_size // 2
        
        print(f"Initialized with configuration:")
        print(f"  Server URL: {config.server_url}")
        print(f"  Model: {config.model_name}")
        print(f"  Max tokens: {config.max_tokens}")
        print(f"  Chunk size: {self.chunk_size}, Stride: {self.stride}")
        
        # Test connection to LMStudio
        self._test_connection()
    
    def _test_connection(self):
        """Test connection to LMStudio server."""
        try:
            models = self.client.models.list()
            print(f"✅ Connected to LMStudio server")
            model_names = [model.id for model in models.data]
            print(f"Available models: {model_names}")
            
            if self.config.model_name not in model_names and model_names:
                print(f"⚠️ Warning: Model '{self.config.model_name}' not found in available models")
                print(f"Available models: {model_names}")
                print(f"Using first available model: {model_names[0]}")
                self.config.model_name = model_names[0]
                
        except Exception as e:
            print(f"❌ Failed to connect to LMStudio server: {e}")
            print(f"Please make sure LMStudio is running on {self.config.server_url}")
    
    def summarize_chunk(self, chunk_text: str, context: str = "") -> str:
        """
        Generate a summary for a single text chunk.
        
        Args:
            chunk_text: Text chunk to summarize
            context: Additional context information
            
        Returns:
            Generated summary text
        """
        system_prompt = "你是一个擅长阅读和总结小说的助手。请用简洁明了的中文为文本生成摘要。"
        
        if context:
            user_prompt = (
                f"上下文信息：{context}\n\n"
                f"请阅读以下文本片段，然后用简短语言为该片段生成一段摘要：\n\n"
                f"{chunk_text}\n\n"
                f"请用中文回答，突出主要情节和人物动作。"
            )
        else:
            user_prompt = (
                f"请阅读以下文本片段，然后用简短语言为该片段生成一段摘要：\n\n"
                f"{chunk_text}\n\n"
                f"请用中文回答，突出主要情节和人物动作。"
            )
        
        try:
            response = self.client.chat.completions.create(
                model=self.config.model_name,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                temperature=0.3,
                max_tokens=self.config.max_tokens,
                timeout=self.config.api_timeout
            )
            
            summary = response.choices[0].message.content.strip()
            return summary
            
        except Exception as e:
            print(f"Error generating summary: {e}")
            return "摘要生成失败。"
    
    def aggregate_summaries(self, summaries_list: List[str], chapter_title: str) -> str:
        """
        Aggregate multiple chunk summaries into a coherent chapter summary.
        
        Args:
            summaries_list: List of individual chunk summaries
            chapter_title: Title of the chapter
            
        Returns:
            Aggregated chapter summary
        """
        if len(summaries_list) == 1:
            return summaries_list[0]
        
        joined = "\n".join(f"{i+1}. {summary}" for i, summary in enumerate(summaries_list))
        
        system_prompt = "你是一个擅长整合和总结的助手。请将多个片段摘要整合成一个连贯的章节小结。"
        
        user_prompt = (
            f"章节标题：{chapter_title}\n\n"
            f"以下是该章节被拆分成多个片段后，各片段的摘要：\n\n"
            f"{joined}\n\n"
            f"请整合这些摘要，生成一段连贯的章节小结，用简洁语言概括全部情节，"
            f"保持逻辑顺序，控制在250字以内。"
        )
        
        try:
            response = self.client.chat.completions.create(
                model=self.config.model_name,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                temperature=0.3,
                max_tokens=self.config.max_tokens,
                timeout=self.config.api_timeout
            )
            
            chapter_summary = response.choices[0].message.content.strip()
            return chapter_summary
            
        except Exception as e:
            print(f"Error aggregating summaries: {e}")
            return "章节摘要生成失败。"
    
    def process_chapter(self, title: str, content: str, progress_desc: str = "") -> str:
        """
        Process a single chapter and generate its summary.
        
        Args:
            title: Chapter title
            content: Chapter content
            progress_desc: Description for progress display
            
        Returns:
            Chapter summary
        """
        total_tokens = estimate_tokens(content, 'gpt-3.5-turbo')  # Use for estimation
        
        if total_tokens <= self.chunk_size:
            # Direct summarization for short chapters
            summary = self.summarize_chunk(content)
        else:
            # Rolling window approach for long chapters
            chunks = split_into_chunks(
                content, 
                chunk_size=self.chunk_size, 
                stride=self.stride, 
                model_name='gpt-3.5-turbo'  # Use for chunking estimation
            )
            
            part_summaries = []
            for i, chunk in enumerate(chunks):
                # Add some delay to avoid overwhelming the local server
                if i > 0:
                    time.sleep(2)
                
                part_summary = self.summarize_chunk(chunk, f"这是{title}的第{i+1}部分")
                part_summaries.append(part_summary)
            
            # Aggregate summaries
            summary = self.aggregate_summaries(part_summaries, title)
        
        return summary
    
    def process_novel(self, novel_path: str, output_path: str = None, resume: bool = True) -> str:
        """
        Process an entire novel and generate chapter summaries with checkpoint support.
        
        Args:
            novel_path: Path to the novel text file
            output_path: Output path for the summary file
            resume: Whether to resume from checkpoint if available
            
        Returns:
            Path to the generated summary file
        """
        if output_path is None:
            base_name = os.path.splitext(os.path.basename(novel_path))[0]
            output_path = f"summaries/{base_name}_summary.md"
        
        # Create necessary directories
        create_directories()
        
        # Initialize checkpoint manager
        checkpoint_manager = CheckpointManager(novel_path, output_path)
        
        # Check for existing checkpoint
        has_checkpoint, checkpoint_data = checkpoint_manager.load_checkpoint()
        
        if has_checkpoint and resume:
            print(f"📂 发现断点文件，从第 {checkpoint_data['chapter_index']} 章继续处理...")
            chapters = []  # Will be loaded later
            results = checkpoint_data['processed_results']
            start_index = checkpoint_data['chapter_index']
            metadata = checkpoint_data['metadata']
        else:
            print(f"🚀 开始处理小说: {novel_path}")
            results = []
            start_index = 0
            metadata = {
                "model": self.config.model_name,
                "server_url": self.config.server_url,
                "max_tokens": self.config.max_tokens
            }
        
        # Load and split novel (always needed for continuing)
        print("正在加载小说文本...")
        full_text = load_novel(novel_path)
        print(f"文本总长度: {len(full_text)} 字符")
        
        print("正在分割章节...")
        chapters = split_into_chapters(full_text)
        print(f"共找到 {len(chapters)} 个章节")
        
        if len(chapters) == 0:
            raise ValueError("未找到任何章节，请检查文本格式或章节标题模式")
        
        # Update metadata if this is a fresh start
        if not has_checkpoint or not resume:
            metadata.update({
                "total_chapters": len(chapters),
                "start_time": time.strftime('%Y-%m-%d %H:%M:%S')
            })
        
        # Process chapters with progress bar
        try:
            with tqdm(total=len(chapters), initial=start_index, 
                     desc="处理章节", unit="章", 
                     bar_format="{l_bar}{bar}| {n_fmt}/{total_fmt} [{elapsed}<{remaining}]") as pbar:
                
                for i in range(start_index, len(chapters)):
                    title, content = chapters[i]
                    
                    # Update progress bar description
                    pbar.set_description(f"处理第 {i+1} 章")
                    
                    if not content.strip():
                        print(f"  章节 {i+1} 内容为空，跳过")
                        pbar.update(1)
                        continue
                    
                    try:
                        # Process chapter
                        summary = self.process_chapter(title, content, f"第{i+1}章")
                        results.append((title, summary))
                        
                        # Save checkpoint after each chapter
                        checkpoint_manager.save_checkpoint(
                            chapter_index=i + 1,
                            total_chapters=len(chapters),
                            processed_results=results,
                            metadata=metadata
                        )
                        
                        # Update progress bar
                        pbar.update(1)
                        pbar.set_postfix({
                            "已完成": f"{len(results)}/{len(chapters)}",
                            "成功率": f"{len(results)/(i+1)*100:.1f}%"
                        })
                        
                    except KeyboardInterrupt:
                        print(f"\n⚠️ 用户中断处理，已保存到第 {i+1} 章的进度")
                        print(f"📁 断点文件: {checkpoint_manager.checkpoint_file}")
                        print(f"📄 阶段性结果: {checkpoint_manager.progress_file}")
                        return checkpoint_manager.progress_file
                        
                    except Exception as e:
                        print(f"  处理第 {i+1} 章失败: {e}")
                        results.append((title, "本章摘要生成失败"))
                        pbar.update(1)
        
        except KeyboardInterrupt:
            print(f"\n⚠️ 用户中断处理")
            return checkpoint_manager.progress_file
        
        # Save final results
        print(f"\n💾 保存最终结果到: {output_path}")
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(f"# 小说章节摘要 (Generated by {self.config.model_name})\n\n")
            f.write(f"**原文件**: {novel_path}\n")
            f.write(f"**使用模型**: {self.config.model_name}\n")
            f.write(f"**服务器**: {self.config.server_url}\n")
            f.write(f"**生成时间**: {time.strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f"**总章节数**: {len(results)}\n")
            f.write(f"**最大Token数**: {self.config.max_tokens}\n\n")
            f.write("---\n\n")
            
            for title, summary in results:
                f.write(f"## {title}\n\n")
                f.write(f"**摘要**: {summary}\n\n")
        
        # Clear checkpoint files after successful completion
        checkpoint_manager.clear_checkpoint()
        
        print(f"✅ 处理完成！生成了 {len(results)} 个章节的摘要")
        print(f"📄 最终文件: {output_path}")
        
        return output_path


def main():
    """Main function to run the novel summarizer."""
    sample_novel_name = random.choice(os.listdir("novels"))
    if len(sys.argv) < 2:
        print("使用方法: python main.py <小说文件路径> [输出文件路径] [服务器URL] [模型名称] [选项]")
        print("\n示例:")
        print(f"  python main.py novels/{sample_novel_name}")
        print(f"  python main.py novels/{sample_novel_name} summaries/my_summary.md")
        print(f"  python main.py novels/{sample_novel_name} summaries/my_summary.md http://localhost:1234")
        print(f"  python main.py novels/{sample_novel_name} summaries/my_summary.md http://localhost:1234 qwen3-8b")
        print("\n选项:")
        print("  --no-resume    不使用断点续传，重新开始处理")
        print("\n环境变量配置:")
        print("  LMSTUDIO_BASE_URL=http://localhost  # 服务器基础URL")
        print("  LMSTUDIO_PORT=1234                  # 服务器端口")
        print("  MODEL_NAME=qwen3-8b                 # 模型名称")
        print("  MAX_TOKENS=32786                    # 最大tokens")
        print("  CHUNK_BUFFER=500                    # 分块缓冲区")
        print("\n断点续传功能:")
        print("  - 处理过程中会自动保存进度到 checkpoints/ 目录")
        print("  - 如果中断，重新运行相同命令即可从断点继续")
        print("  - 使用 --no-resume 选项可以重新开始处理")
        print("  - 阶段性结果保存在 checkpoints/ 目录的 *_progress.md 文件中")
        return
    
    novel_path = sys.argv[1]
    output_path = sys.argv[2] if len(sys.argv) > 2 and not sys.argv[2].startswith('--') else None
    server_url = None
    model = None
    resume = True
    
    # Parse additional arguments
    for i, arg in enumerate(sys.argv[2:], 2):
        if arg == '--no-resume':
            resume = False
        elif arg.startswith('http'):
            server_url = arg
        elif not arg.startswith('--') and i == 3:  # Third non-option argument
            server_url = arg
        elif not arg.startswith('--') and i == 4:  # Fourth non-option argument
            model = arg
    
    if not os.path.exists(novel_path):
        print(f"错误: 文件 {novel_path} 不存在")
        return
    
    try:
        # Create configuration
        config = NovelSummarizerConfig()
        
        # Update from command line arguments
        config.update_from_args(server_url=server_url, model=model)
        
        # Initialize summarizer
        summarizer = NovelSummarizer(config)
        result_path = summarizer.process_novel(novel_path, output_path, resume=resume)
        
        print(f"\n✅ 成功完成！")
        print(f"📄 摘要文件: {result_path}")
        
    except Exception as e:
        print(f"❌ 错误: {e}")
        return 1


if __name__ == "__main__":
    main() 